//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://firstallied.com/webservices/", ConfigurationName="FirstAllied.FileServer.FileIOSoap")]
    public interface FileIOSoap {
        
        // CODEGEN: Generating message contract since element name sLocation from namespace http://firstallied.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/FolderExists", ReplyAction="*")]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsResponse FolderExists(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/FolderExists", ReplyAction="*")]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsResponse> FolderExistsAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsRequest request);
        
        // CODEGEN: Generating message contract since element name sLocation from namespace http://firstallied.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/FileExists", ReplyAction="*")]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsResponse FileExists(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/FileExists", ReplyAction="*")]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsResponse> FileExistsAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsRequest request);
        
        // CODEGEN: Generating message contract since element name sLocation from namespace http://firstallied.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/FileSize", ReplyAction="*")]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeResponse FileSize(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/FileSize", ReplyAction="*")]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeResponse> FileSizeAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeRequest request);
        
        // CODEGEN: Generating message contract since element name sLocation from namespace http://firstallied.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/CountChunks", ReplyAction="*")]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksResponse CountChunks(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/CountChunks", ReplyAction="*")]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksResponse> CountChunksAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksRequest request);
        
        // CODEGEN: Generating message contract since element name sLocation from namespace http://firstallied.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/DownloadChunkBytes", ReplyAction="*")]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesResponse DownloadChunkBytes(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/DownloadChunkBytes", ReplyAction="*")]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesResponse> DownloadChunkBytesAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesRequest request);
        
        // CODEGEN: Generating message contract since element name sLocation from namespace http://firstallied.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/DownloadChunk", ReplyAction="*")]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkResponse DownloadChunk(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/DownloadChunk", ReplyAction="*")]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkResponse> DownloadChunkAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/UploadChunk", ReplyAction="*")]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkResponse UploadChunk(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/UploadChunk", ReplyAction="*")]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkResponse> UploadChunkAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkRequest request);
        
        // CODEGEN: Generating message contract since element name sLocation from namespace http://firstallied.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/UploadChunkWithFilename", ReplyAction="*")]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameResponse UploadChunkWithFilename(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://firstallied.com/webservices/UploadChunkWithFilename", ReplyAction="*")]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameResponse> UploadChunkWithFilenameAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FolderExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FolderExists", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsRequestBody Body;
        
        public FolderExistsRequest() {
        }
        
        public FolderExistsRequest(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class FolderExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sSubFolder;
        
        public FolderExistsRequestBody() {
        }
        
        public FolderExistsRequestBody(string sLocation, string sSubFolder) {
            this.sLocation = sLocation;
            this.sSubFolder = sSubFolder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FolderExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FolderExistsResponse", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsResponseBody Body;
        
        public FolderExistsResponse() {
        }
        
        public FolderExistsResponse(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class FolderExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FolderExistsResult;
        
        public FolderExistsResponseBody() {
        }
        
        public FolderExistsResponseBody(bool FolderExistsResult) {
            this.FolderExistsResult = FolderExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileExists", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsRequestBody Body;
        
        public FileExistsRequest() {
        }
        
        public FileExistsRequest(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class FileExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sSubFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sFileName;
        
        public FileExistsRequestBody() {
        }
        
        public FileExistsRequestBody(string sLocation, string sSubFolder, string sFileName) {
            this.sLocation = sLocation;
            this.sSubFolder = sSubFolder;
            this.sFileName = sFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileExistsResponse", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsResponseBody Body;
        
        public FileExistsResponse() {
        }
        
        public FileExistsResponse(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class FileExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FileExistsResult;
        
        public FileExistsResponseBody() {
        }
        
        public FileExistsResponseBody(bool FileExistsResult) {
            this.FileExistsResult = FileExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileSizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileSize", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeRequestBody Body;
        
        public FileSizeRequest() {
        }
        
        public FileSizeRequest(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class FileSizeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sSubFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sFileName;
        
        public FileSizeRequestBody() {
        }
        
        public FileSizeRequestBody(string sLocation, string sSubFolder, string sFileName) {
            this.sLocation = sLocation;
            this.sSubFolder = sSubFolder;
            this.sFileName = sFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileSizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileSizeResponse", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeResponseBody Body;
        
        public FileSizeResponse() {
        }
        
        public FileSizeResponse(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class FileSizeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long FileSizeResult;
        
        public FileSizeResponseBody() {
        }
        
        public FileSizeResponseBody(long FileSizeResult) {
            this.FileSizeResult = FileSizeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountChunksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountChunks", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksRequestBody Body;
        
        public CountChunksRequest() {
        }
        
        public CountChunksRequest(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class CountChunksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sSubFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int iChunkSize;
        
        public CountChunksRequestBody() {
        }
        
        public CountChunksRequestBody(string sLocation, string sSubFolder, string sFileName, int iChunkSize) {
            this.sLocation = sLocation;
            this.sSubFolder = sSubFolder;
            this.sFileName = sFileName;
            this.iChunkSize = iChunkSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountChunksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountChunksResponse", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksResponseBody Body;
        
        public CountChunksResponse() {
        }
        
        public CountChunksResponse(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class CountChunksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CountChunksResult;
        
        public CountChunksResponseBody() {
        }
        
        public CountChunksResponseBody(int CountChunksResult) {
            this.CountChunksResult = CountChunksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadChunkBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadChunkBytes", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesRequestBody Body;
        
        public DownloadChunkBytesRequest() {
        }
        
        public DownloadChunkBytesRequest(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class DownloadChunkBytesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sSubFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long iBeginByte;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long iEndByte;
        
        public DownloadChunkBytesRequestBody() {
        }
        
        public DownloadChunkBytesRequestBody(string sLocation, string sSubFolder, string sFileName, long iBeginByte, long iEndByte) {
            this.sLocation = sLocation;
            this.sSubFolder = sSubFolder;
            this.sFileName = sFileName;
            this.iBeginByte = iBeginByte;
            this.iEndByte = iEndByte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadChunkBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadChunkBytesResponse", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesResponseBody Body;
        
        public DownloadChunkBytesResponse() {
        }
        
        public DownloadChunkBytesResponse(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class DownloadChunkBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownloadChunkBytesResult;
        
        public DownloadChunkBytesResponseBody() {
        }
        
        public DownloadChunkBytesResponseBody(byte[] DownloadChunkBytesResult) {
            this.DownloadChunkBytesResult = DownloadChunkBytesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadChunkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadChunk", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkRequestBody Body;
        
        public DownloadChunkRequest() {
        }
        
        public DownloadChunkRequest(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class DownloadChunkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sSubFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int iChunkSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int iStartChunk;
        
        public DownloadChunkRequestBody() {
        }
        
        public DownloadChunkRequestBody(string sLocation, string sSubFolder, string sFileName, int iChunkSize, int iStartChunk) {
            this.sLocation = sLocation;
            this.sSubFolder = sSubFolder;
            this.sFileName = sFileName;
            this.iChunkSize = iChunkSize;
            this.iStartChunk = iStartChunk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadChunkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadChunkResponse", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkResponseBody Body;
        
        public DownloadChunkResponse() {
        }
        
        public DownloadChunkResponse(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class DownloadChunkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownloadChunkResult;
        
        public DownloadChunkResponseBody() {
        }
        
        public DownloadChunkResponseBody(byte[] DownloadChunkResult) {
            this.DownloadChunkResult = DownloadChunkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadChunkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadChunk", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkRequestBody Body;
        
        public UploadChunkRequest() {
        }
        
        public UploadChunkRequest(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class UploadChunkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sSubFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] baChunk;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int iChunkSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int iStartChunk;
        
        public UploadChunkRequestBody() {
        }
        
        public UploadChunkRequestBody(string sLocation, string sSubFolder, string sFileName, byte[] baChunk, int iChunkSize, int iStartChunk) {
            this.sLocation = sLocation;
            this.sSubFolder = sSubFolder;
            this.sFileName = sFileName;
            this.baChunk = baChunk;
            this.iChunkSize = iChunkSize;
            this.iStartChunk = iStartChunk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadChunkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadChunkResponse", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkResponseBody Body;
        
        public UploadChunkResponse() {
        }
        
        public UploadChunkResponse(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class UploadChunkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UploadChunkResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sFileName;
        
        public UploadChunkResponseBody() {
        }
        
        public UploadChunkResponseBody(int UploadChunkResult, string sFileName) {
            this.UploadChunkResult = UploadChunkResult;
            this.sFileName = sFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadChunkWithFilenameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadChunkWithFilename", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameRequestBody Body;
        
        public UploadChunkWithFilenameRequest() {
        }
        
        public UploadChunkWithFilenameRequest(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class UploadChunkWithFilenameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sSubFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] baChunk;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int iChunkSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int iStartChunk;
        
        public UploadChunkWithFilenameRequestBody() {
        }
        
        public UploadChunkWithFilenameRequestBody(string sLocation, string sSubFolder, string sFileName, byte[] baChunk, int iChunkSize, int iStartChunk) {
            this.sLocation = sLocation;
            this.sSubFolder = sSubFolder;
            this.sFileName = sFileName;
            this.baChunk = baChunk;
            this.iChunkSize = iChunkSize;
            this.iStartChunk = iStartChunk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadChunkWithFilenameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadChunkWithFilenameResponse", Namespace="http://firstallied.com/webservices/", Order=0)]
        public CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameResponseBody Body;
        
        public UploadChunkWithFilenameResponse() {
        }
        
        public UploadChunkWithFilenameResponse(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstallied.com/webservices/")]
    public partial class UploadChunkWithFilenameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UploadChunkWithFilenameResult;
        
        public UploadChunkWithFilenameResponseBody() {
        }
        
        public UploadChunkWithFilenameResponseBody(int UploadChunkWithFilenameResult) {
            this.UploadChunkWithFilenameResult = UploadChunkWithFilenameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileIOSoapChannel : CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileIOSoapClient : System.ServiceModel.ClientBase<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap>, CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap {
        
        public FileIOSoapClient() {
        }
        
        public FileIOSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileIOSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileIOSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileIOSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsResponse CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.FolderExists(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsRequest request) {
            return base.Channel.FolderExists(request);
        }
        
        public bool FolderExists(string sLocation, string sSubFolder) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsResponse retVal = ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).FolderExists(inValue);
            return retVal.Body.FolderExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsResponse> CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.FolderExistsAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsRequest request) {
            return base.Channel.FolderExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsResponse> FolderExistsAsync(string sLocation, string sSubFolder) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FolderExistsRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            return ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).FolderExistsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsResponse CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.FileExists(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsRequest request) {
            return base.Channel.FileExists(request);
        }
        
        public bool FileExists(string sLocation, string sSubFolder, string sFileName) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsResponse retVal = ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).FileExists(inValue);
            return retVal.Body.FileExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsResponse> CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.FileExistsAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsRequest request) {
            return base.Channel.FileExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsResponse> FileExistsAsync(string sLocation, string sSubFolder, string sFileName) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileExistsRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            return ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).FileExistsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeResponse CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.FileSize(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeRequest request) {
            return base.Channel.FileSize(request);
        }
        
        public long FileSize(string sLocation, string sSubFolder, string sFileName) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeResponse retVal = ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).FileSize(inValue);
            return retVal.Body.FileSizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeResponse> CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.FileSizeAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeRequest request) {
            return base.Channel.FileSizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeResponse> FileSizeAsync(string sLocation, string sSubFolder, string sFileName) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileSizeRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            return ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).FileSizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksResponse CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.CountChunks(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksRequest request) {
            return base.Channel.CountChunks(request);
        }
        
        public int CountChunks(string sLocation, string sSubFolder, string sFileName, int iChunkSize) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            inValue.Body.iChunkSize = iChunkSize;
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksResponse retVal = ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).CountChunks(inValue);
            return retVal.Body.CountChunksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksResponse> CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.CountChunksAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksRequest request) {
            return base.Channel.CountChunksAsync(request);
        }
        
        public System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksResponse> CountChunksAsync(string sLocation, string sSubFolder, string sFileName, int iChunkSize) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.CountChunksRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            inValue.Body.iChunkSize = iChunkSize;
            return ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).CountChunksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesResponse CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.DownloadChunkBytes(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesRequest request) {
            return base.Channel.DownloadChunkBytes(request);
        }
        
        public byte[] DownloadChunkBytes(string sLocation, string sSubFolder, string sFileName, long iBeginByte, long iEndByte) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            inValue.Body.iBeginByte = iBeginByte;
            inValue.Body.iEndByte = iEndByte;
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesResponse retVal = ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).DownloadChunkBytes(inValue);
            return retVal.Body.DownloadChunkBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesResponse> CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.DownloadChunkBytesAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesRequest request) {
            return base.Channel.DownloadChunkBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesResponse> DownloadChunkBytesAsync(string sLocation, string sSubFolder, string sFileName, long iBeginByte, long iEndByte) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkBytesRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            inValue.Body.iBeginByte = iBeginByte;
            inValue.Body.iEndByte = iEndByte;
            return ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).DownloadChunkBytesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkResponse CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.DownloadChunk(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkRequest request) {
            return base.Channel.DownloadChunk(request);
        }
        
        public byte[] DownloadChunk(string sLocation, string sSubFolder, string sFileName, int iChunkSize, int iStartChunk) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            inValue.Body.iChunkSize = iChunkSize;
            inValue.Body.iStartChunk = iStartChunk;
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkResponse retVal = ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).DownloadChunk(inValue);
            return retVal.Body.DownloadChunkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkResponse> CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.DownloadChunkAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkRequest request) {
            return base.Channel.DownloadChunkAsync(request);
        }
        
        public System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkResponse> DownloadChunkAsync(string sLocation, string sSubFolder, string sFileName, int iChunkSize, int iStartChunk) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.DownloadChunkRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            inValue.Body.iChunkSize = iChunkSize;
            inValue.Body.iStartChunk = iStartChunk;
            return ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).DownloadChunkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkResponse CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.UploadChunk(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkRequest request) {
            return base.Channel.UploadChunk(request);
        }
        
        public int UploadChunk(string sLocation, string sSubFolder, ref string sFileName, byte[] baChunk, int iChunkSize, int iStartChunk) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            inValue.Body.baChunk = baChunk;
            inValue.Body.iChunkSize = iChunkSize;
            inValue.Body.iStartChunk = iStartChunk;
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkResponse retVal = ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).UploadChunk(inValue);
            sFileName = retVal.Body.sFileName;
            return retVal.Body.UploadChunkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkResponse> CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.UploadChunkAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkRequest request) {
            return base.Channel.UploadChunkAsync(request);
        }
        
        public System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkResponse> UploadChunkAsync(string sLocation, string sSubFolder, string sFileName, byte[] baChunk, int iChunkSize, int iStartChunk) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            inValue.Body.baChunk = baChunk;
            inValue.Body.iChunkSize = iChunkSize;
            inValue.Body.iStartChunk = iStartChunk;
            return ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).UploadChunkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameResponse CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.UploadChunkWithFilename(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameRequest request) {
            return base.Channel.UploadChunkWithFilename(request);
        }
        
        public int UploadChunkWithFilename(string sLocation, string sSubFolder, string sFileName, byte[] baChunk, int iChunkSize, int iStartChunk) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            inValue.Body.baChunk = baChunk;
            inValue.Body.iChunkSize = iChunkSize;
            inValue.Body.iStartChunk = iStartChunk;
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameResponse retVal = ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).UploadChunkWithFilename(inValue);
            return retVal.Body.UploadChunkWithFilenameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameResponse> CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap.UploadChunkWithFilenameAsync(CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameRequest request) {
            return base.Channel.UploadChunkWithFilenameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameResponse> UploadChunkWithFilenameAsync(string sLocation, string sSubFolder, string sFileName, byte[] baChunk, int iChunkSize, int iStartChunk) {
            CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameRequest inValue = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameRequest();
            inValue.Body = new CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.UploadChunkWithFilenameRequestBody();
            inValue.Body.sLocation = sLocation;
            inValue.Body.sSubFolder = sSubFolder;
            inValue.Body.sFileName = sFileName;
            inValue.Body.baChunk = baChunk;
            inValue.Body.iChunkSize = iChunkSize;
            inValue.Body.iStartChunk = iStartChunk;
            return ((CmsFileMigration.DownloadFilesFromFileServer.FirstAllied.FileServer.FileIOSoap)(this)).UploadChunkWithFilenameAsync(inValue);
        }
    }
}
