USE [Innova]
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Affiliate' AND COLUMN_NAME = 'ShortName' )
BEGIN
	ALTER TABLE dbo.Affiliate ADD ShortName VARCHAR( 10 ) NOT NULL CONSTRAINT [DF_Affiliate_ShortName] DEFAULT ''
END
GO

IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Affiliate' AND COLUMN_NAME = 'SAMLConfigName' )
BEGIN
	ALTER TABLE dbo.Affiliate DROP COLUMN SAMLConfigName
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Affiliate' AND COLUMN_NAME = 'SAMLConfigurationID' )
BEGIN
	ALTER TABLE dbo.Affiliate ADD SAMLConfigurationID INT
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Affiliate_SAMLConfigurationID' )
BEGIN
	ALTER TABLE dbo.Affiliate ADD CONSTRAINT FK_Affiliate_SAMLConfigurationID FOREIGN KEY( SAMLConfigurationID ) 
		REFERENCES app.Configuration(ConfigurationID )
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Affiliate' AND COLUMN_NAME = 'CreateUserID' )
BEGIN
	ALTER TABLE dbo.Affiliate ADD CreateUserID INT NOT NULL CONSTRAINT [DF_Affiliate_CreateUserID] DEFAULT 0
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Affiliate' AND COLUMN_NAME = 'CreateDate' )
BEGIN
	ALTER TABLE dbo.Affiliate ADD CreateDate DATETIME NOT NULL CONSTRAINT [DF_Affiliate_CreateDate] DEFAULT GETDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Affiliate' AND COLUMN_NAME = 'CreateDateUTC' )
BEGIN
	ALTER TABLE dbo.Affiliate ADD CreateDateUTC DATETIME NOT NULL CONSTRAINT [DF_Affiliate_CreateDateUTC] DEFAULT GETUTCDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Affiliate' AND COLUMN_NAME = 'ModifyUserID' )
BEGIN
	ALTER TABLE dbo.Affiliate ADD ModifyUserID INT NOT NULL CONSTRAINT [DF_Affiliate_ModifyUserID] DEFAULT 0
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Affiliate' AND COLUMN_NAME = 'ModifyDate' )
BEGIN
	ALTER TABLE dbo.Affiliate ADD ModifyDate DATETIME NOT NULL CONSTRAINT [DF_Affiliate_ModifyDate] DEFAULT GETDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Affiliate' AND COLUMN_NAME = 'ModifyDateUTC' )
BEGIN
	ALTER TABLE dbo.Affiliate ADD ModifyDateUTC DATETIME NOT NULL CONSTRAINT [DF_Affiliate_ModifyDateUTC] DEFAULT GETUTCDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Feature' AND COLUMN_NAME = 'PlaceholderValue' )
BEGIN
	ALTER TABLE dbo.Feature ADD [PlaceholderValue] [varchar](512) NOT NULL CONSTRAINT DF_Feature_PlaceholderValue DEFAULT ''
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AffiliateFeature' AND COLUMN_NAME = 'Value' )
	AND EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AffiliateFeature' AND COLUMN_NAME = 'DisabledMessage' )
BEGIN
	EXECUTE sp_rename 'dbo.AffiliateFeature.DisabledMessage' , 'Value', 'COLUMN'
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AffiliateFeature' AND COLUMN_NAME = 'CreateUserID' )
BEGIN
	ALTER TABLE dbo.AffiliateFeature ADD CreateUserID INT NOT NULL CONSTRAINT [DF_AffiliateFeature_CreateUserID] DEFAULT 0
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AffiliateFeature' AND COLUMN_NAME = 'CreateDate' )
BEGIN
	ALTER TABLE dbo.AffiliateFeature ADD CreateDate DATETIME NOT NULL CONSTRAINT [DF_AffiliateFeature_CreateDate] DEFAULT GETDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AffiliateFeature' AND COLUMN_NAME = 'CreateDateUTC' )
BEGIN
	ALTER TABLE dbo.AffiliateFeature ADD CreateDateUTC DATETIME NOT NULL CONSTRAINT [DF_AffiliateFeature_CreateDateUTC] DEFAULT GETUTCDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AffiliateFeature' AND COLUMN_NAME = 'ModifyUserID' )
BEGIN
	ALTER TABLE dbo.AffiliateFeature ADD ModifyUserID INT NOT NULL CONSTRAINT [DF_AffiliateFeature_ModifyUserID] DEFAULT 0
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AffiliateFeature' AND COLUMN_NAME = 'ModifyDate' )
BEGIN
	ALTER TABLE dbo.AffiliateFeature ADD ModifyDate DATETIME NOT NULL CONSTRAINT [DF_AffiliateFeature_ModifyDate] DEFAULT GETDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AffiliateFeature' AND COLUMN_NAME = 'ModifyDateUTC' )
BEGIN
	ALTER TABLE dbo.AffiliateFeature ADD ModifyDateUTC DATETIME NOT NULL CONSTRAINT [DF_AffiliateFeature_ModifyDateUTC] DEFAULT GETUTCDATE()
END
GO

IF NOT EXISTS( SELECT * FROM sys.indexes WHERE name = 'IX_AffiliateBusinessPlanObjective_AffiliateID' )
BEGIN
	CREATE NONCLUSTERED INDEX IX_AffiliateBusinessPlanObjective_AffiliateID
		ON dbo.AffiliateBusinessPlanObjective ( AffiliateID )
			INCLUDE( BusinessPlanObjectiveID, AutoTrackingEnabled )
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_AffiliateBusinessPlanObjective_BusinessPlanObjectiveID' )
BEGIN
	ALTER TABLE dbo.AffiliateBusinessPlanObjective ADD CONSTRAINT FK_AffiliateBusinessPlanObjective_BusinessPlanObjectiveID FOREIGN KEY( BusinessPlanObjectiveID ) REFERENCES dbo.BusinessPlanObjective( BusinessPlanObjectiveID )
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_AffiliateBusinessPlanObjective_AffiliateID' )
BEGIN
	ALTER TABLE dbo.AffiliateBusinessPlanObjective ADD CONSTRAINT FK_AffiliateBusinessPlanObjective_AffiliateID FOREIGN KEY( AffiliateID ) REFERENCES dbo.Affiliate( AffiliateID )
END
GO

IF EXISTS ( SELECT * FROM sys.indexes WHERE name = 'UX_Affiliate_BrokerDealerID' )
BEGIN
	DROP INDEX dbo.Affiliate.UX_Affiliate_BrokerDealerID
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Affiliate' AND COLUMN_NAME = 'ExternalID' )
	AND EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Affiliate' AND COLUMN_NAME = 'BrokerDealerID' )
BEGIN
	EXECUTE sp_rename 'dbo.Affiliate.BrokerDealerID' , 'ExternalID', 'COLUMN'
END
GO

IF NOT EXISTS( SELECT * FROM sys.indexes WHERE name = 'UX_Affiliate_ExternalID' )
	AND EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Affiliate' AND COLUMN_NAME = 'ExternalID' ) 
BEGIN
	CREATE UNIQUE NONCLUSTERED INDEX [UX_Affiliate_ExternalID] ON [dbo].[Affiliate] ( [ExternalID] )
		INCLUDE( [Name] ) WHERE [ExternalID] IS NOT NULL
END
GO
