USE [Innova]
GO

IF NOT EXISTS
(
	SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_View_CategoryID' AND CONSTRAINT_SCHEMA = 'rpt'
)
BEGIN
	ALTER TABLE [rpt].[View] ADD CONSTRAINT [FK_View_CategoryID] FOREIGN KEY( CategoryID ) REFERENCES [rpt].[Category]( CategoryID )
END
GO

IF NOT EXISTS
(
	SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ViewFilter_ViewID' AND CONSTRAINT_SCHEMA = 'rpt'
)
BEGIN
	ALTER TABLE [rpt].[ViewFilter] ADD CONSTRAINT [FK_ViewFilter_ViewID] FOREIGN KEY( ViewID ) REFERENCES [rpt].[View]( ViewID )
END
GO

IF NOT EXISTS
(
	SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ViewFilter_FilterID' AND CONSTRAINT_SCHEMA = 'rpt'
)
BEGIN
	ALTER TABLE [rpt].[ViewFilter] ADD CONSTRAINT [FK_ViewFilter_FilterID] FOREIGN KEY( FilterID ) REFERENCES [rpt].[Filter]( FilterID )
END
GO

IF NOT EXISTS
(
	SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ViewColumn_ViewID' AND CONSTRAINT_SCHEMA = 'rpt'
)
BEGIN
	ALTER TABLE [rpt].[ViewColumn] ADD CONSTRAINT [FK_ViewColumn_ViewID] FOREIGN KEY( ViewID ) REFERENCES [rpt].[View]( ViewID )
END
GO

IF NOT EXISTS
(
	SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_ViewColumn_ColumnID' AND CONSTRAINT_SCHEMA = 'rpt'
)
BEGIN
	ALTER TABLE [rpt].[ViewColumn] ADD CONSTRAINT [FK_ViewColumn_ColumnID] FOREIGN KEY( ColumnID ) REFERENCES [rpt].[Column]( ColumnID )
END
GO

IF NOT EXISTS( SELECT * FROM sys.indexes WHERE name = 'IX_Category_ParentCategoryID' )
BEGIN
	CREATE NONCLUSTERED INDEX [IX_Category_ParentCategoryID] ON [rpt].[Category] ( [ParentCategoryID] )
END
GO

IF NOT EXISTS( SELECT * FROM sys.indexes WHERE name = 'IX_View_CategoryID' )
BEGIN
	CREATE NONCLUSTERED INDEX [IX_View_CategoryID] ON [rpt].[View] ( [CategoryID] )
END
GO

IF NOT EXISTS( SELECT * FROM sys.indexes WHERE name = 'IX_ViewFilter_ViewID' )
BEGIN
	CREATE NONCLUSTERED INDEX [IX_ViewFilter_ViewID] ON [rpt].[ViewFilter] ( [ViewID] )
END
GO

IF NOT EXISTS( SELECT * FROM sys.indexes WHERE name = 'IX_ViewColumn_ViewID' )
BEGIN
	CREATE NONCLUSTERED INDEX [IX_ViewColumn_ViewID] ON [rpt].[ViewColumn] ( [ViewID] )
END
GO
