USE [Innova]
GO

IF NOT EXISTS( SELECT * FROM sys.indexes WHERE name = 'IX_SurveyResponseAnswer_SurveyResponseID' )
BEGIN
	CREATE NONCLUSTERED INDEX IX_SurveyResponseAnswer_SurveyResponseID
		ON [dbo].[SurveyResponseAnswer] ([SurveyResponseID])
			INCLUDE ([SurveyQuestionID],[Answer])
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Survey' AND COLUMN_NAME = 'CreateUserID' )
BEGIN
	ALTER TABLE dbo.Survey ADD CreateUserID INT NOT NULL CONSTRAINT [DF_Survey_CreateUserID] DEFAULT 0
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Survey' AND COLUMN_NAME = 'CreateDate' )
BEGIN
	ALTER TABLE dbo.Survey ADD CreateDate DATETIME NOT NULL CONSTRAINT [DF_Survey_CreateDate] DEFAULT GETDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Survey' AND COLUMN_NAME = 'CreateDateUTC' )
BEGIN
	ALTER TABLE dbo.Survey ADD CreateDateUTC DATETIME NOT NULL CONSTRAINT [DF_Survey_CreateDateUTC] DEFAULT GETUTCDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Survey' AND COLUMN_NAME = 'ModifyUserID' )
BEGIN
	ALTER TABLE dbo.Survey ADD ModifyUserID INT NOT NULL CONSTRAINT [DF_Survey_ModifyUserID] DEFAULT 0
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Survey' AND COLUMN_NAME = 'ModifyDate' )
BEGIN
	ALTER TABLE dbo.Survey ADD ModifyDate DATETIME NOT NULL CONSTRAINT [DF_Survey_ModifyDate] DEFAULT GETDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Survey' AND COLUMN_NAME = 'ModifyDateUTC' )
BEGIN
	ALTER TABLE dbo.Survey ADD ModifyDateUTC DATETIME NOT NULL CONSTRAINT [DF_Survey_ModifyDateUTC] DEFAULT GETUTCDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SurveyPageScoreRange' AND COLUMN_NAME = 'CreateUserID' )
BEGIN
	ALTER TABLE dbo.SurveyPageScoreRange ADD CreateUserID INT NOT NULL CONSTRAINT [DF_SurveyPageScoreRange_CreateUserID] DEFAULT 0
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SurveyPageScoreRange' AND COLUMN_NAME = 'CreateDate' )
BEGIN
	ALTER TABLE dbo.SurveyPageScoreRange ADD CreateDate DATETIME NOT NULL CONSTRAINT [DF_SurveyPageScoreRange_CreateDate] DEFAULT GETDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SurveyPageScoreRange' AND COLUMN_NAME = 'CreateDateUTC' )
BEGIN
	ALTER TABLE dbo.SurveyPageScoreRange ADD CreateDateUTC DATETIME NOT NULL CONSTRAINT [DF_SurveyPageScoreRange_CreateDateUTC] DEFAULT GETUTCDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SurveyPageScoreRange' AND COLUMN_NAME = 'ModifyUserID' )
BEGIN
	ALTER TABLE dbo.SurveyPageScoreRange ADD ModifyUserID INT NOT NULL CONSTRAINT [DF_SurveyPageScoreRange_ModifyUserID] DEFAULT 0
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SurveyPageScoreRange' AND COLUMN_NAME = 'ModifyDate' )
BEGIN
	ALTER TABLE dbo.SurveyPageScoreRange ADD ModifyDate DATETIME NOT NULL CONSTRAINT [DF_SurveyPageScoreRange_ModifyDate] DEFAULT GETDATE()
END
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SurveyPageScoreRange' AND COLUMN_NAME = 'ModifyDateUTC' )
BEGIN
	ALTER TABLE dbo.SurveyPageScoreRange ADD ModifyDateUTC DATETIME NOT NULL CONSTRAINT [DF_SurveyPageScoreRange_ModifyDateUTC] DEFAULT GETUTCDATE()
END
GO

IF NOT EXISTS( SELECT * FROM sys.foreign_keys WHERE name = 'FK_SurveyPageScoreRange_SurveyPageID' )
	ALTER TABLE [dbo].[SurveyPageScoreRange]  ADD  CONSTRAINT [FK_SurveyPageScoreRange_SurveyPageID] FOREIGN KEY([SurveyPageID]) REFERENCES [dbo].[SurveyPage] ([SurveyPageID])
GO
