USE Innova
GO

-- Add OldID Columns
IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME ='BusinessPlan' AND COLUMN_NAME = 'OldID' )
	ALTER TABLE dbo.BusinessPlan ADD OldID INT
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME ='BusinessPlanEmployee' AND COLUMN_NAME = 'OldID' )
	ALTER TABLE dbo.BusinessPlanEmployee ADD OldID INT
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME ='BusinessPlanEmployeeRole' AND COLUMN_NAME = 'OldID' )
	ALTER TABLE dbo.BusinessPlanEmployeeRole ADD OldID INT
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME ='BusinessPlanObjective' AND COLUMN_NAME = 'OldID' )
	ALTER TABLE dbo.BusinessPlanObjective ADD OldID INT
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME ='BusinessPlanStrategy' AND COLUMN_NAME = 'OldID' )
	ALTER TABLE dbo.BusinessPlanStrategy ADD OldID INT
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME ='BusinessPlanTactic' AND COLUMN_NAME = 'OldID' )
	ALTER TABLE dbo.BusinessPlanTactic ADD OldID INT
GO

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME ='BusinessPlanSwot' AND COLUMN_NAME = 'OldID' )
	ALTER TABLE dbo.BusinessPlanSwot ADD OldID INT
GO
